sonar.projectKey=marestail
sonar.projectName=marestail
sonar.sources=marestail
sonar.tests=tests
sonar.test.inclusions=tests/**/test_*.py
sonar.exclusions=**/__pycache__/**,**/mutants/**,**/.venv/**,tools/samples/**,templates/**,roles/**,perf/**,marestail/tui/**,marestail/cs/**,marestail/erl/**,marestail/ex/**,marestail/js/**,marestail/jvm/**,marestail/rb/**,marestail/rs/**
sonar.python.version=3.12
sonar.python.coverage.reportPaths=.marestail/py-coverage.xml
sonar.sourceEncoding=UTF-8
