sonar.projectKey=change-me
sonar.sources=server,client/app/src
sonar.tests=server/services/tests,client/app/src
sonar.test.inclusions=**/*_tests.py,**/*.test.ts,**/*.test.tsx
sonar.exclusions=**/node_modules/**,**/mutants/**,**/dist/**,**/.venv/**,**/reports/**
sonar.python.version=3.12
sonar.python.coverage.reportPaths=.marestail/py-coverage.xml
sonar.javascript.lcov.reportPaths=.marestail/ts-coverage/lcov.info
sonar.ruby.coverage.reportPaths=coverage/.resultset.json
sonar.erlang.eunit.reportsfolder=.marestail
sonar.erlang.eunit.coverdata.filename=eunit.coverdata
sonar.sourceEncoding=UTF-8
